scripts/push: apply fix
When I changed the `Push` FAKE target to an fsx script, a confusing
error from FAKE happened while sending the package to NuGet:

```
  Successfully created package '/home/runner/work/FSharpLint/FSharpLint/out/dotnet-fsharplint.0.24.0.nupkg'.
Finished (Success) 'DotNet:pack' in 00:00:16.8873157
System.Exception: Cannot set 'Fake.Core.Trace.TraceSecrets' as we have no fake context
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1448.Invoke(String message)
   at Fake.Core.TraceSecrets.register(String replacement, String secret) in D:\a\FAKE\FAKE\src\app\Fake.Core.Trace\TraceListener.fs:line 351
   at Fake.DotNet.Paket.pushFiles(FSharpFunc`2 setParams, IEnumerable`1 files) in D:\a\FAKE\FAKE\src\app\Fake.DotNet.Paket\Paket.fs:line 275
   at Fake.DotNet.Paket.push(FSharpFunc`2 setParams) in D:\a\FAKE\FAKE\src\app\Fake.DotNet.Paket\Paket.fs:line 331
   at <StartupCode$FSI_0006>.$FSI_0006.main@() in /home/runner/work/FSharpLint/FSharpLint/scripts/push.fsx:line 32
Stopped due to error
```

We need to make a FAKE-Context as per FAKE's guide [1].

[1]: https://fake.build/guide/fake-debugging.html#Run-script-without-fake-exe-via-fsi